#!/bin/bash
res=`tccli cvm DescribeInstancesStatus --filter 'InstanceStatusSet[*].InstanceId'`
res2=`echo $res | sed s/[[:space:]]//g`
echo $res2
if [[ $1 == "d" ]]
then
  tes=`tccli cvm TerminateInstances --InstanceIds $res2`
  echo $tes
fi
